// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://jcqpuqhdfveleusjsxeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjcXB1cWhkZnZlbGV1c2pzeGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5NDg3ODIsImV4cCI6MjA5NjUyNDc4Mn0.u0hL3IV8Vdzpoh0Tr1fPUetcbAVbL5Cc0RFjBT3YZH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
